### ISSUE TITLE
Končanje projekta

### ISSUE THREAD

**Issue by majbc1999** [katjakranjec/instrukcije-opb#3]
Živjo, Janoš mi je povedal, da nameravata končati projekt in iti na ustni zagovor. Pregledal sem ga in je dobro narejen, vse poizvedbe delujejo, našel pa sem še dve malenkosti, ki bi jih bilo dobro popraviti:

- ko skušam rezervirati termin na `uporabnik/rezerviraj`, mi za default datum vrže 26.7., čeprav je danes 6.8. Dobro bi bilo, da se datum nastavi na "danes"
- opazil sem, da je mogoče rezervirati tudi termin iz preteklosti. To bi bilo dobro odpraviti. To lahko naredita tako, da se termini iz preteklosti ne pojavijo, ko iščemo proste termine.

Ko to naredita, mi povejta, da preverim in (če bo ustrezno narejeno) odobrim projekt. Sicer pa se vama opravičujem za pozen pregled, zaradi počitnic.

**Comment by katjakranjec** [comment]
Hvala za pregled in popravke. 

Default datumi so zdaj popravljeni pri `uporabnik/rezerviraj` in tudi pri `instruktor/vnesi`, pri čemer sva se odločili da je default datum "jutri" . Izbira datuma tudi ne omogoča izbrati datuma pred "jutri" s čimer je bil rešen tudi drugi problem.  Tudi pri `instruktor/vnesi` zdaj ni več možno vnašati termina za nazaj.

**Comment by majbc1999** [comment]
Super, mislim, da je sedaj vse v redu. @jaanos, lahko ju dodaš na repozitorij, če seveda tudi ti nimaš pripomb. Nato se lahko zmenita s profesorjem Orbanićem za zagovor.

**Comment by jaanos** [comment]
Bom dodal povezavo do projekta na repozitorij predmeta. Če se še nista, se lahko z @alenFMF domenita za termin zagovora. Če bosta do takrat še kaj spreminjali, mi javita, da posodobim povezavo.

Opozoril bi le, da se pri iskanju prostih terminov ne izpišejo termini za prvi izbrani dan.

**Comment by katjakranjec** [comment]
Hvala za opozorilo . Iskanje terminov je zdaj popravljeno in dodano je še urejanje izpisanih terminov po datumu. Do jutrišnjega ustnega izpita ne nameravava spreminjati ničesar več, tako da bi prosili, če @jaanos posodobite povezavo.

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo.
